# Site settings
title: "WolfDWyc"
description: "My personal blog for anything I want."
baseurl:
url: ""
author: ""

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: "test"
issues_repo: "WolfDWyc/WolfDWyc.github.io"

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
